module.exports = {
  name: "Kiri Vadivelu",
  title: "Kiri Vadivelu | For Mayor of Toronto",
  description: "Socialist Solutions to Capitalist Crisis in 21st Century",
  keywords: ["community", "economy", "democracy", "justice", "peace"],
  url: "https://kiri-vadivelu.ca",
  image: "/kiri-vadivelu.jpg",
  rssUrl: "https://kiri-vadivelu.ca/rss.xml",
  feedUrl: "https://kiri-vadivelu.ca/feed.xml",
  feed: {
    subtitle: "Socialist Solutions to Capitalist Crisis in 21st Century",
    filename: "feed.xml",
    path: "/feed.xml",
    id: "https://kiri-vadivelu.ca",
  },
  jsonfeed: {
    path: "/feed.json",
    url: "https://kiri-vadivelu.ca/feed.json",
  },
  author: {
    name: "Kiri Vadivelu",
    email: "office@kiri-vadivelu.ca",
    jobTitle: "Jamstack Engineer",
    employer: "Digital Designers",
    city: "Toronto",
    country: "Canada",
    url: "https://kiri-vadivelu.ca",
    image: "https://kiri-vadivelu.ca/logo.png",
    twitter: "https://twitter.com/kiri_vadivelu",
    facebook: "https://facebook.com/kiri.vadivelu",
    instagram: "https://instagram.com/kiri_vadivelu/",
    linkedin: "https://linkedin.com/in/kiri-vadivelu/",
    copyright: "https:/kiri-vadivelu.ca/legal",
  },
  Publisher: {
    name: "Digital Designers",
    city: "Toronto",
    country: "Canada",
    url: "https://digitaldesigners.ca",
    email: "kiri@digitaldesigners.ca",
    logo: "https://digitaldesigners.ca/logo.png",
    twitter: "https://twitter.com/ddesignersca",
    facebook: "https://facebook.com/digitaldesignersca",
    instagram: "https://instagram.com/digitaldesignersca",
    linkedin: "https://linkedin.com/in/digitaldesignersca",
    copyright: "https://digitaldesigners.ca/terms",
  },
  type: "website",
  local: "en_CA",
  city: "Toronto",
  country: "Canada",
  currentYear() {
    const today = new Date();
    return today.getFullYear();
  },
};
